#!/usr/bin/env python3
"""
AFK Slayer — v3 CLEAN TONAL SFX pack (original synthesis).

HARD RULE: no white/pink noise, no filtered-noise whooshes, no random sources.
Everything is built from sines, soft harmonics, gentle inharmonic bell/wood
partials (still pure tones), short pitch sweeps and <5 ms sine clicks.
Pitches sit in C / F major so the cues fit the bright v3 chillhop bed.

Every file: >=3 ms raised-cosine fade-in, >=15 ms fade-out, 2nd-order HP at
150 Hz (phone speakers), peak -1 dBFS, mono 44.1 kHz, WAV + Ogg Vorbis (q5).

Matches the mob_death v2 aesthetic (soft sine body + mid tone + reward tick +
tiny sine click). mob_death_a|b are NOT regenerated by this script.
"""
from __future__ import annotations

import math
import subprocess
import wave
from pathlib import Path

import numpy as np

SR = 44100
ROOT = Path(__file__).resolve().parent
SFX = ROOT / "sfx"
UI = ROOT / "ui"


def hz(note: str) -> float:
    names = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}
    semis = names[note[0]] + (1 if "#" in note else 0)
    octave = int(note[-1])
    midi = 12 * (octave + 1) + semis
    return 440.0 * 2 ** ((midi - 69) / 12)


# ------------------------------------------------------------ primitives ---
def buf(ms: float) -> np.ndarray:
    return np.zeros(int(round(ms * 0.001 * SR)))


def t_axis(n: int) -> np.ndarray:
    return np.arange(n) / SR


def env(n: int, attack_ms: float, decay_ms: float) -> np.ndarray:
    """Raised-cosine attack then exponential decay."""
    t = t_axis(n)
    e = np.exp(-t / (decay_ms * 0.001))
    na = max(2, int(attack_ms * 0.001 * SR))
    na = min(na, n)
    e[:na] *= 0.5 - 0.5 * np.cos(np.linspace(0, math.pi, na))
    return e


def partials(freq: float, ms: float, spec, attack_ms: float = 2.0) -> np.ndarray:
    """spec = [(ratio, amp, decay_ms), ...] — additive, tonal only."""
    n = int(ms * 0.001 * SR)
    t = t_axis(n)
    out = np.zeros(n)
    for ratio, amp, dec in spec:
        f = freq * ratio
        if f >= SR * 0.45:
            continue
        out += amp * np.sin(2 * math.pi * f * t) * env(n, attack_ms, dec)
    return out


def sweep(f0: float, f1: float, ms: float, decay_ms: float, attack_ms: float = 2.0,
          harm2: float = 0.0) -> np.ndarray:
    """Exponential pitch glide (tonal blip)."""
    n = int(ms * 0.001 * SR)
    t = t_axis(n)
    f = f0 * (f1 / f0) ** (t / (ms * 0.001))
    ph = 2 * math.pi * np.cumsum(f) / SR
    return (np.sin(ph) + harm2 * np.sin(2 * ph)) * env(n, attack_ms, decay_ms)


def click(freq: float = 2600.0, ms: float = 2.5) -> np.ndarray:
    """Tiny sine burst under 5 ms, Hann-windowed (not noise)."""
    n = int(ms * 0.001 * SR)
    return np.sin(2 * math.pi * freq * t_axis(n)) * np.hanning(n)


def bell(freq: float, ms: float, decay_ms: float, sparkle: float = 0.0) -> np.ndarray:
    """Warm bell: fundamental + soft octave/12th + optional gentle inharmonic sparkle."""
    spec = [(1.0, 1.0, decay_ms), (2.0, 0.28, decay_ms * 0.55), (3.0, 0.08, decay_ms * 0.3)]
    if sparkle:
        spec += [(2.76, 0.12 * sparkle, decay_ms * 0.35), (5.40, 0.05 * sparkle, decay_ms * 0.2)]
    return partials(freq, ms, spec, attack_ms=2.0)


def wood(freq: float, ms: float, decay_ms: float) -> np.ndarray:
    """Dry wood-block tock: a few fast-decaying inharmonic partials."""
    return partials(freq, ms, [(1.0, 1.0, decay_ms), (2.32, 0.45, decay_ms * 0.6),
                               (3.95, 0.18, decay_ms * 0.35)], attack_ms=1.0)


def pluck(freq: float, ms: float, decay_ms: float, bend: float = 0.985) -> np.ndarray:
    """Additive plucked string: harmonics 1/k, higher ones die faster, tiny pitch settle."""
    n = int(ms * 0.001 * SR)
    t = t_axis(n)
    fcur = freq * (1 + (1 / bend - 1) * np.exp(-t / 0.012))  # starts slightly sharp
    ph = 2 * math.pi * np.cumsum(fcur) / SR
    out = np.zeros(n)
    for k in range(1, 9):
        if freq * k > 9000:
            break
        out += (1.0 / k) * np.sin(k * ph) * env(n, 1.0, decay_ms / (1 + 0.55 * (k - 1)))
    return out


def place(dest: np.ndarray, src: np.ndarray, at_ms: float, gain: float = 1.0) -> None:
    s = int(at_ms * 0.001 * SR)
    if s >= len(dest):
        return
    m = min(len(src), len(dest) - s)
    dest[s:s + m] += src[:m] * gain


# --------------------------------------------------------------- finalize ---
def highpass_biquad(x: np.ndarray, fc: float = 150.0, q: float = 0.707) -> np.ndarray:
    w0 = 2 * math.pi * fc / SR
    alpha = math.sin(w0) / (2 * q)
    cw = math.cos(w0)
    b0, b1, b2 = (1 + cw) / 2, -(1 + cw), (1 + cw) / 2
    a0, a1, a2 = 1 + alpha, -2 * cw, 1 - alpha
    b0, b1, b2, a1, a2 = b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0
    y = np.zeros_like(x)
    x1 = x2 = y1 = y2 = 0.0
    for i, xi in enumerate(x):
        yi = b0 * xi + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
        y[i] = yi
        x2, x1, y2, y1 = x1, xi, y1, yi
    return y


def finalize(x: np.ndarray, stem: Path, fade_in_ms: float = 3.0, fade_out_ms: float = 15.0) -> dict:
    x = highpass_biquad(x, 150.0)
    ni = int(fade_in_ms * 0.001 * SR)
    no = int(fade_out_ms * 0.001 * SR)
    x[:ni] *= 0.5 - 0.5 * np.cos(np.linspace(0, math.pi, ni))
    x[-no:] *= 0.5 + 0.5 * np.cos(np.linspace(0, math.pi, no))
    x = x * (10 ** (-1.0 / 20) / (np.max(np.abs(x)) + 1e-12))
    stem.parent.mkdir(parents=True, exist_ok=True)
    wav_p, ogg_p = stem.with_suffix(".wav"), stem.with_suffix(".ogg")
    pcm = np.round(np.clip(x, -1, 1) * 32767).astype(np.int16)
    with wave.open(str(wav_p), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())
    subprocess.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-i", str(wav_p),
                    "-c:a", "libvorbis", "-q:a", "5", "-ar", str(SR), "-ac", "1", str(ogg_p)],
                   check=True)
    return {"id": stem.name, "ms": round(1000 * len(x) / SR, 1)}


# ------------------------------------------------------------------ cues ---
def bolt_fire(f0: float) -> np.ndarray:
    """Soft short tonal 'pew': quick downward sine blip. Quiet, unobtrusive."""
    out = buf(85)
    place(out, sweep(f0, f0 * 0.62, 70, 22, attack_ms=2.0, harm2=0.10), 0)
    return out


def bolt_hit(f: float) -> np.ndarray:
    """Soft tonal thock: short sine thud (~200–300 Hz) + tiny sine click."""
    out = buf(115)
    place(out, sweep(f, f * 0.8, 100, 32, attack_ms=2.0), 0)
    place(out, partials(f * 2.0, 60, [(1.0, 1.0, 16)]), 0, 0.25)
    place(out, click(2600, 2.5), 0, 0.22)
    return out


def briar_swing() -> np.ndarray:
    """Soft metallic ping + short thud. No whoosh."""
    out = buf(170)
    place(out, sweep(230, 180, 90, 30), 0, 0.8)
    ping = partials(hz("C6"), 160, [(1.0, 1.0, 55), (2.76, 0.30, 25), (5.40, 0.10, 12)])
    place(out, ping, 12, 0.55)
    place(out, click(3000, 2.0), 12, 0.12)
    return out


def quill_arrow_fire() -> np.ndarray:
    """Soft plucked-string twang."""
    out = buf(95)
    place(out, pluck(hz("G4"), 95, 55), 0)
    return out


def quill_arrow_hit() -> np.ndarray:
    """Dry wooden tock."""
    out = buf(110)
    place(out, wood(640, 110, 20), 0)
    place(out, partials(300, 80, [(1.0, 1.0, 18)]), 0, 0.45)
    return out


def task_complete() -> np.ndarray:
    """Two-note rising bell chime C5 → G5."""
    out = buf(430)
    place(out, bell(hz("C5"), 430, 170), 0, 0.85)
    place(out, bell(hz("G5"), 320, 190), 110, 1.0)
    place(out, click(2400, 2.0), 0, 0.10)
    return out


def monster_unlock() -> np.ndarray:
    """Three-note soft arpeggio F5 – A5 – C6."""
    out = buf(370)
    for i, n in enumerate(("F5", "A5", "C6")):
        place(out, bell(hz(n), 370 - 75 * i, 140), 75 * i, 0.8 + 0.1 * i)
    return out


def signature_drop() -> np.ndarray:
    """Sparkly bell arpeggio — rare loot, the most exciting cue."""
    out = buf(490)
    notes = ("C5", "E5", "G5", "C6", "E6")
    for i, n in enumerate(notes):
        at = 55 * i
        place(out, bell(hz(n), 490 - at, 190, sparkle=1.0), at, 0.7 + 0.07 * i)
    # shimmer: soft high G6/C7 dyad with gentle tremolo, tonal only
    shn = int(0.26 * SR)
    t = t_axis(shn)
    trem = 0.75 + 0.25 * np.sin(2 * math.pi * 18 * t)
    sh = (np.sin(2 * math.pi * hz("G6") * t) + 0.7 * np.sin(2 * math.pi * hz("C7") * t)) * trem
    sh *= env(shn, 25, 120)
    place(out, sh, 200, 0.18)
    return out


def chest_open() -> np.ndarray:
    """Wood click, then a soft two-note chime F5 → C6."""
    out = buf(330)
    place(out, wood(900, 60, 12), 0, 0.8)
    place(out, click(2200, 2.0), 0, 0.15)
    place(out, bell(hz("F5"), 260, 120), 65, 0.8)
    place(out, bell(hz("C6"), 200, 120), 140, 0.9)
    return out


def upgrade_purchase() -> np.ndarray:
    """Coin-like double ping E6 → A6."""
    out = buf(245)
    coin = [(1.0, 1.0, 55), (2.0, 0.25, 30), (2.72, 0.10, 18)]
    place(out, partials(hz("E6"), 150, coin), 0, 0.85)
    place(out, partials(hz("A6"), 175, coin), 70, 1.0)
    return out


def empty_task_nudge() -> np.ndarray:
    """Very soft wood knock."""
    out = buf(140)
    place(out, wood(480, 140, 22), 0)
    return out


def tab_switch() -> np.ndarray:
    """Tiny soft tick."""
    out = buf(55)
    place(out, partials(1760, 55, [(1.0, 1.0, 9), (2.0, 0.2, 5)], attack_ms=1.0), 0)
    place(out, partials(880, 55, [(1.0, 1.0, 10)], attack_ms=1.0), 0, 0.5)
    return out


def intro_step_complete() -> np.ndarray:
    """Clean soft rising two-note confirm G5 → C6."""
    out = buf(240)
    place(out, bell(hz("G5"), 240, 90), 0, 0.8)
    place(out, bell(hz("C6"), 160, 100), 80, 1.0)
    return out


CUES = {
    SFX / "bolt_fire_a": lambda: bolt_fire(hz("C6")),
    SFX / "bolt_fire_b": lambda: bolt_fire(hz("A5")),
    SFX / "bolt_fire_c": lambda: bolt_fire(hz("G5")),
    SFX / "bolt_hit_a": lambda: bolt_hit(hz("C4") - 8),       # ~254 Hz
    SFX / "bolt_hit_b": lambda: bolt_hit(hz("A3") + 10),      # ~230 Hz
    SFX / "bolt_hit_c": lambda: bolt_hit(hz("D4") - 10),      # ~284 Hz
    SFX / "briar_swing": briar_swing,
    SFX / "quill_arrow_fire": quill_arrow_fire,
    SFX / "quill_arrow_hit": quill_arrow_hit,
    SFX / "task_complete": task_complete,
    SFX / "monster_unlock": monster_unlock,
    SFX / "signature_drop": signature_drop,
    SFX / "chest_open": chest_open,
    SFX / "upgrade_purchase": upgrade_purchase,
    UI / "empty_task_nudge": empty_task_nudge,
    UI / "tab_switch": tab_switch,
    UI / "intro_step_complete": intro_step_complete,
}


def main() -> None:
    for stem, fn in CUES.items():
        meta = finalize(fn(), stem)
        print(f"{stem.relative_to(ROOT)}  {meta['ms']} ms")


if __name__ == "__main__":
    main()
